#!/bin/bash

mkdir ./opalang
wget http://doc.opalang.org/dl/linux/opa-1.1.1.x64.run
chmod +x ./opa-1.1.1.x64.run
vulcan build -v -s ./ -c "mkdir /app/mlstate-opa && yes '' | ./opa-1.1.1.x64.run" -p /app/mlstate-opa
